language: php

services:
  - mongodb

php:
  - '7.0'

before-install:
  - sudo apt-get install php-mongo
  - composer self-update


install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
