language: php

services:
  - mongodb

php:
  - '7.0'

before-install:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update


install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
